name: Deploy to Public IP

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git curl

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'  # Replace with your Go version

      - name: Build the application
        run: |
          go build -o my-app

      - name: Copy application to server
        env:
          SERVER_IP: ${{ secrets.SERVER_PUBLIC_IP }}  # Store your server's public IP in GitHub Secrets
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # Store your SSH private key in GitHub Secrets
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa my-app ubuntu@$SERVER_IP:/home/ubuntu/my-app

      - name: Run the application on the server
        env:
          SERVER_IP: ${{ secrets.SERVER_PUBLIC_IP }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@$SERVER_IP "chmod +x /home/ubuntu/my-app && nohup /home/ubuntu/my-app &"
